export const CREATE_ROUTE = '@ROUTE_FLOW/CREATE_ROUTE';
export const UPDATE_ROUTE = '@ROUTE_FLOW/UPDATE_ROUTE';
export const UPDATE_ROUTE_STATUS = '@ROUTE_FLOW/UPDATE_ROUTE_STATUS';
export const SIGN_OUT = '@ROUTE_FLOW/SIGN_OUT';
export const UPDATE_VEHICLE_ID = '@ROUTE_FLOW/UPDATE_VEHICLE_ID';
